s|\"\[JIRA_USER_ID\]\"|'$RD_OPTION_JIRA_USER_ID'|
s/\[JIRA_API_KEY\]/$RD_OPTION_JIRA_API_KEY/
s/\[BITBUCKET_USER_ID\]/$RD_OPTION_BITBUCKET_USER_ID/
s/\[BITBUCKET_API_PASSWORD\]/$RD_OPTION_BITBUCKET_API_PASSWORD/
s/\[DATABASE_PASSWORD\]/$RD_OPTION_DATABASE_PASSWORD/
s/\[DATABASE_HOST]/$RD_OPTION_DATABASE_HOST/